// Run from the repository root: node interface/tests/library.mjs.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import fs from 'node:fs';
import vm from 'node:vm';
const require = createRequire(import.meta.url);
const L = require('../render/library.js');
const markdownit = require('../vendor/markdown-it/markdown-it.umd.min.js');
const katex = require('../vendor/katex/katex.min.js');
const files = [{root:'science', path:'topic/Index.md', title:'Science', aliases:['Primer']},
  {root:'arts', path:'topic/Index.md', title:'Arts'}, {root:'science', path:'topic/Other.md'}];
const current = files[0];
assert.equal(L.resolve('Index', current, files, true).kind, 'ambiguous');
assert.equal(L.resolve('arts/topic/Index', current, files, true).file, files[1]);
assert.equal(L.resolve('Index.md', current, files).file, current);
assert.equal(L.resolve('Other.md#Details', current, files).file, files[2]);
assert.equal(L.resolve('Primer', current, files, true).file, current);
assert.equal(L.resolve('Absent', current, files, true).kind, 'missing');
assert.equal(L.resolve('../../private/Secret.md', current, files).kind, 'missing');
assert.equal(L.resolve('javascript:alert(1)', current, files, true).kind, 'missing');
assert.equal(L.resolve('#Details', current, files).anchor, 'Details');
assert.equal(new URLSearchParams(L.route({root:'a&b', path:'why? #.md'}).split('?')[1]).get('note'), 'why? #.md');
assert.deepEqual(L.groups(files, 'science').docs, []);
assert.equal(L.groups(files, 'science', 'topic').docs.length, 2);
const rendered = L.render(`# Heading\n\n<script>alert(1)</script>\n\n[[arts/topic/Index|Read]] · [[Index]] · [[Absent]]\n\n[local](Other.md#Details) [external](https://example.org) [bad](javascript:alert(1))\n\n- parent\n  - child\n\n| A | B |\n|---|---|\n| one | two |\n\n$$\n\\hat{x} = \\frac{1}{2}\n$$\n\nInline $a_b$; code \`$not_math$\`.\n\n\`\`\`mermaid\ngraph TD\nA-->B\n\`\`\`\n\n# Heading\n`, current, files, {markdownit, katex});
assert.ok(!rendered.html.includes('<script>'));
assert.ok(!rendered.html.includes('href="javascript:'));
assert.match(rendered.html, /&lt;script&gt;/);
assert.match(rendered.html, /<table>/);
assert.match(rendered.html, /<li>parent\s*<ul>/);
assert.match(rendered.html, /class="katex-display"/);
assert.match(rendered.html, /<code>\$not_math\$<\/code>/);
assert.match(rendered.html, /note-diagram/);
assert.match(rendered.html, /rel="noopener noreferrer"/);
assert.deepEqual(rendered.problems.map(p => p.kind), ['ambiguous', 'missing']);
assert.deepEqual(rendered.outline.map(h => h.id), ['note-heading-heading', 'note-heading-heading-1']);
const numbered = {root:'science', path:'2.1-Calculus.md'};
assert.equal(L.resolve('Calculus', current, [...files, numbered], true).file, numbered);
assert.equal(L.resolve('3-Calculus', current, [...files, numbered], true).file, numbered);
const tableWiki = L.render('| Link | Why |\n|---|---|\n| [[arts/topic/Index|Arts]] | Read |', current, files, {markdownit, katex});
assert.match(tableWiki.html, />Arts<\/a>/);
assert.equal((tableWiki.html.match(/<td>/g) || []).length, 2);
const code = L.render('```\n| [[Index|Label]] |\n```', current, files, {markdownit, katex});
assert.match(code.html, /\| \[\[Index\|Label\]\] \|/);
assert.equal(code.problems.length, 0);
const unsafeMath = L.render('$\\href{javascript:alert(1)}{click}$', current, files, {markdownit, katex});
assert.ok(!unsafeMath.html.includes('href="javascript:'));
const callout = L.render('> [!TIP] Read this.\n', current, files, {markdownit, katex});
assert.match(callout.html, /class="callout-label">TIP<\/strong> Read this/);
// Exercise the classic-script entry point too: lexical globals differ from window properties.
const browser = vm.createContext({markdownit, katex, URLSearchParams});
for (const name of ['escape.js', 'library.js']) vm.runInContext(fs.readFileSync(new URL('../render/' + name, import.meta.url), 'utf8'), browser);
assert.match(vm.runInContext("Library.render('[[Missing]]', null, []).html", browser), /note-unresolved/);
console.log('Library: identity, ambiguity, navigation, safe rendering, math, nested lists, tables and diagram fallback pass.');
